### PR TITLE
 Update .env to fix manifest error on docker-compose

### PR DESCRIPTION
**Pull request by hashoshi**
Image for 2.2.11 is no longer available, which throws ERROR: Service 'authority0' failed to build: manifest for parity/parity:v2.2.11 not found when building using 'docker-compose up -d'

Thanks for this repo - it's a huge timesaver

### CODE REVIEW

**Comment by Pzixel** [comment]
Yeah, we know.

We don't update since we have some issues with 2.4.x+ so we don't upgrade version in the master branch. People may choose whatever version they want.

Maybe we need upgrade version anyway. Need more investigation.

> Thanks for this repo - it's a huge timesaver

Thanks to you, we're glad we could help.

**Comment by SwaroopH** [comment]
@Pzixel the latest stable that just came out (2.4.8) has a fix for Aura. Should we update to that?

**Comment by Pzixel** [comment]
I think it's fine as it is. I will want updating it later on on 2.5.X or something. It's just to make sure default master branch is working. Version requires tuning anyway. For example my contracts don't work with 2.3.X and higher, and I have no idea why. I don't have time to investigate it now so I'm stick with 2.2.11. Other people may have different issues and may wish stick with different versions. So it's up to them anyway.

**Comment by SwaroopH** [comment]
@Pzixel feel free to share them via gist. Happy to run this through @EthVigil's backend and give you results through different compilers. Unless there's a fork like #24 that requires a change in EVM, Parity (and geth) have no awareness of solidity, only the EVM.

**Comment by Pzixel** [comment]
I'l try to run my code on latest version and I'l tell you if it goes wrong. Maybe they fixed something.

Thanks for cooperation.

**Pull request merged**
